#:schema node_modules/wrangler/config-schema.json
name = "g7flix"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "1444cb3a35c9401c8284106d8f88a8e2" }
]

[assets]
directory = "./public"
